use_frameworks!

target 'BeanstalkEngageiOSSDK_Example' do
  pod 'BeanstalkEngageiOSSDK', :path => '../'

  target 'BeanstalkEngageiOSSDK_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '2.3'
    end
  end
end
