use_frameworks!
platform :ios, '9.0'

target 'BeanstalkEngageiOSSDK_Example' do
  pod 'PKHUD', '~> 4.2.0'
  pod 'BeanstalkEngageiOSSDK', :path => '../'
  pod 'GoogleSignIn', '4.1.0'
end

target 'BeanstalkEngageiOSSDK_Tests' do
  pod 'PKHUD', '~> 4.2.0'
  pod 'BeanstalkEngageiOSSDK', :path => '../'
  pod 'BeanstalkEngageiOSSDK/Testing', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0.1'
    end
  end
end
