use_frameworks!

target 'BeanstalkEngageiOSSDK_Example' do
  pod 'BeanstalkEngageiOSSDK', :path => '../'
end

target 'BeanstalkEngageiOSSDK_Tests' do
  pod 'BeanstalkEngageiOSSDK', :path => '../'
  pod 'BeanstalkEngageiOSSDK/Testing', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0.1'
    end
  end
end
