/* Auto-generated */

import Foundation

enum BELocKey: String, BELocKeyProtocol {
  public func getRawValue() -> String {
    return self.rawValue 
  }  
  
  case login_failed = "login_failed"
  case login_failed_text = "login_failed_text"
  case error_store_is_not_alive_title = "error_store_is_not_alive_title"
  case error_store_is_not_alive_message = "error_store_is_not_alive_message"
  case too_late_to_cancel = "too_late_to_cancel"
  case mobile_ordering_not_available_today_error = "mobile_ordering_not_available_today_error"
  case ordering_no_available = "ordering_no_available"
  case pickup_time_expired = "pickup_time_expired"
  case error_please_verify_parameters = "error_please_verify_parameters"
  case error_api_username_must_be_provided = "error_api_username_must_be_provided"
  case error_invalid_request_title = "error_invalid_request_title"
  case error_no_contact_ID_is_stored_in_session_title = "error_no_contact_ID_is_stored_in_session_title"
  case error_no_API_username_provided_title = "error_no_API_username_provided_title"
  case error_update_failed = "error_update_failed"
  case error_contact_ID_should_be_provided_by_session = "error_contact_ID_should_be_provided_by_session"
  case error_sorry_an_error_occurred_while_processing_your_request = "error_sorry_an_error_occurred_while_processing_your_request"
  case error_connection_unavailable = "error_connection_unavailable"
  case error_unknown = "error_unknown"
  case error_failed_to_delete_contact = "error_failed_to_delete_contact"
  case error_failed_to_fetch_contact = "error_failed_to_fetch_contact"
  case error_unable_to_sign_up_user = "error_unable_to_sign_up_user"
  case error_this_email_is_already_registered = "error_this_email_is_already_registered"
  case error_this_phone_is_already_registered = "error_this_phone_is_already_registered"
  case error_unable_to_retrieve_profile = "error_unable_to_retrieve_profile"
  case error_unable_to_update_password = "error_unable_to_update_password"
  case error_unable_to_reset_password = "error_unable_to_reset_password"
  case error_retrieving_cards_information = "error_retrieving_cards_information"
  case error_generating_barcode = "error_generating_barcode"
  case error_retrieving_stores_information = "error_retrieving_stores_information"
  case failed_to_track_transaction = "failed_to_track_transaction"
  case failed_to_send_support_request = "failed_to_send_support_request"
  case error_bad_request_title = "error_bad_request_title"
  case error_connection_failed_title = "error_connection_failed_title"
  case error_create_contact_failed_title = "error_create_contact_failed_title"
  case error_delete_contact_failed_title = "error_delete_contact_failed_title"
  case error_update_contact_failed_title = "error_update_contact_failed_title"
  case error_fetch_contact_failed_title = "error_fetch_contact_failed_title"
  case error_registration_title = "error_registration_title"
  case error_profile_title = "error_profile_title"
  case error_update_profile_title = "error_update_profile_title"
  case error_password_update_title = "error_password_update_title"
  case error_password_reset_title = "error_password_reset_title"
  case error_cards_error_title = "error_cards_error_title"
  case error_payment_title = "error_payment_title"
  case error_find_stores_title = "error_find_stores_title"
  case error_track_transaction_title = "error_track_transaction_title"
  case error_support_request_title = "error_support_request_title"
}
